//Generated by DynTFTCodeGen.

unit DynTFTTextInputFonts;

//This unit should not be compiled for microcontroller.

interface

{$IFNDEF UserTFTCommands}  //this can be a project-level definition
  {$DEFINE mikroTFT}
{$ENDIF}


uses
  Graphics
  {$IFDEF mikroTFT} 
    , TFT
  {$ELSE}
    , {$INCLUDE UserDrawingUnits.inc}
  {$ENDIF}
  ;


const
  CAllFontSettings: array[-1..0] of TDynTFTFontSettings = (
    ( //TFT_fallbackFont  (Fallback font, used when the property mentions an undefined font.)
      FontName: 'Tahoma';
      IdentifierName: 'TFT_defaultFont';
      FontSize: 8;
      Bold: False;
      Italic: False;
      Underline: False;
      StrikeOut: True;
      Charset: 1;
      Pitch: TFontPitch(0)
    )
    ,
    ( //@Tahoma8
      FontName: 'Tahoma';
      IdentifierName: 'Tahoma8';
      FontSize: 8;
      Bold: False;
      Italic: False;
      Underline: False;
      StrikeOut: False;
      Charset: 1;
      Pitch: TFontPitch(0)
    )
  );

var
  Tahoma8_Font: TDynTFTFontSettings;

implementation


var
  i: Integer;

initialization
  Tahoma8_Font := CAllFontSettings[0];
end.

